name: Build React App

on:
  push:
    branches:
      - '**/**'
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - with: 
        node-version: "20"
      - name: Install deps
        run: npm i
      - name: Build projetc
        run: npm run build
          

      